CREATE database pwin;


CREATE SCHEMA greyhound;







CREATE TABLE GREYHOUND.RAW_RACING_INFORMATION (

DATE_RACING		VARCHAR(20)		NOT NULL,
TIME_RACING		VARCHAR(10) 	NOT NULL,
LOCAL_RACING	VARCHAR(80)		NOT NULL,
ORDER_RACING	VARCHAR(10) 	NOT NULL,
GRADE_RACING	VARCHAR(10) 	NOT NULL,
DISTANCE_RACING	VARCHAR(10) 	NOT NULL,
URL_RACING      VARCHAR(1000)   NOT NULL,

TRAP			INTEGER,
POSITION		INTEGER,
NAME			VARCHAR(100),
AGE				NUMERIC(4,2),
WEIGHT 			NUMERIC(6,2),
BEND			VARCHAR(10),
TIME_			NUMERIC(6,2),
SPLIT			NUMERIC(6,2)

);
